"""Add relationships and order items

Revision ID: 8e2127f98969
Revises: 
Create Date: 2024-06-23 09:11:30.785319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e2127f98969'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('product_id', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('orders_ibfk_2', 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    op.drop_column('orders', 'quantity')
    op.add_column('products', sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.drop_column('products', 'total_price')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.add_column('products', sa.Column('total_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('products', 'stock')
    op.drop_column('products', 'price')
    op.add_column('orders', sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('product_id', mysql.VARCHAR(length=60), nullable=False))
    op.create_foreign_key('orders_ibfk_2', 'orders', 'products', ['product_id'], ['id'])
    op.drop_table('cart_items')
    # ### end Alembic commands ###
